spring:
  security:
    oauth2:
      client:
        provider:
          azure-ad:
            authorization-uri: https://login.microsoftonline.com/6f4432dc-20d2-441d-b1db-ac3380ba633d/oauth2/v2.0/authorize
            token-uri: https://login.microsoftonline.com/6f4432dc-20d2-441d-b1db-ac3380ba633d/oauth2/v2.0/token
            jwk-set-uri: https://login.microsoftonline.com/6f4432dc-20d2-441d-b1db-ac3380ba633d/discovery/v2.0/keys
        registration:
          azure-ad:
            provider: azure-ad
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid
server:
  forward-headers-strategy: native